Update custom-builder.yaml

diff --git a/.github/workflows/custom-builder.yaml b/.github/workflows/custom-builder.yaml
--- a/.github/workflows/custom-builder.yaml
+++ b/.github/workflows/custom-builder.yaml
@@ -4,8 +4,8 @@
 # This is free software, licensed under the MIT License.
 # See /LICENSE for more information.
 #
-
 name: Custom Builder
+
 permissions:
   contents: write
   packages: write
@@ -56,10 +56,6 @@ on:
         description: "Rebuild Toolchain"
         type: boolean
         default: false
-      split_toolchain:
-        description: "Split toolchain image into 1GB parts"
-        type: boolean
-        default: true
       vermagic:
         description: "Replace Vermagic"
         type: boolean
@@ -71,7 +67,7 @@ on:
 
 env:
   SOURCE_URL: ${{ github.event.inputs.source }}
-  SOURCE_ORIGIN: "https://github.com/openwrt/openwrt"
+  SOURCE_ORIGIN: https://github.com/openwrt/openwrt
   SOURCE_BRANCH: ${{ github.event.inputs.branch }}
   FEEDS_SH: feeds.sh
   FEEDS_PKG_SH: feeds_pkg.sh
@@ -81,7 +77,6 @@ env:
   DIY_SH: ${{ github.event.inputs.diy }}
   FIRMWARE_RELEASE: ${{ github.event.inputs.firmware_release }}
   TOOLCHAIN_REBUILD: ${{ github.event.inputs.toolchain_rebuild }}
-  SPLIT_TOOLCHAIN: ${{ github.event.inputs.split_toolchain }}
   TOOLCHAIN_TAG: toolchain
   VERMAGIC: ${{ github.event.inputs.vermagic }}
   VERMAGIC_OPT: ${{ github.event.inputs.vermagic_opt }}
@@ -105,6 +100,7 @@ jobs:
       DEVICE_SUBTARGET: ${{ steps.env.outputs.DEVICE_SUBTARGET }}
       TOOLCHAIN_IMAGE: ${{ steps.env.outputs.TOOLCHAIN_IMAGE }}
       BUILD_DATE: ${{ steps.env.outputs.BUILD_DATE }}
+
     steps:
       - name: Initialize Environment
         run: |
@@ -175,16 +171,20 @@ jobs:
 
       - name: Set Custom Build Information
         run: |
+          echo "Setting custom build information..."
           echo "KBUILD_BUILD_USER=dbai" >> $GITHUB_ENV
           echo "KBUILD_BUILD_HOST=tim-mawar" >> $GITHUB_ENV
           echo "SOURCE_DATE_EPOCH=$(date -d '1998-05-04' +%s)" >> $GITHUB_ENV
+          echo "Build user set to: dbai"
+          echo "Build host set to: tim-mawar"
+          echo "Build date set to: 4 Mei 1998"
 
       - name: Setup ccache
         run: |
           mkdir -p ~/.ccache
-          echo "CCACHE_DIR=~/.ccache" >> $GITHUB_ENV
-          echo "CCACHE_COMPRESS=1" >> $GITHUB_ENV
-          echo "USE_CCACHE=1" >> $GITHUB_ENV
+          echo "export CCACHE_DIR=~/.ccache" >> $GITHUB_ENV
+          echo "export CCACHE_COMPRESS=1" >> $GITHUB_ENV
+          echo "export USE_CCACHE=1" >> $GITHUB_ENV
           ccache -M 2G
           ccache -z
 
@@ -201,28 +201,28 @@ jobs:
       - name: Generate Toolchain Configuration
         run: |
           if [[ "$CONFIG_LINK" == "true" && -n "$CONFIG_URL" ]]; then
-            curl -fsSL "$CONFIG_URL" -o "$OPENWRT_ROOT_PATH/.config"
+            curl -fsSL $CONFIG_URL -o $OPENWRT_ROOT_PATH/.config
           else
-            cp "./config/$CONFIG_FILE" "$OPENWRT_ROOT_PATH/.config"
+            cp ./config/$CONFIG_FILE $OPENWRT_ROOT_PATH/.config
           fi
-          echo -e "\nCONFIG_ALL=y\nCONFIG_ALL_NONSHARED=y" >> "$OPENWRT_ROOT_PATH/.config"
-          cd "$OPENWRT_ROOT_PATH"
+          echo -e "\nCONFIG_ALL=y\nCONFIG_ALL_NONSHARED=y" >> $OPENWRT_ROOT_PATH/.config
+          cd $OPENWRT_ROOT_PATH
           make defconfig
 
       - name: Generate Variables
         id: env
         run: |
-          export SOURCE_OWNER=$(echo "$SOURCE_URL" | awk -F '/' '{print $(NF-1)}')
+          export SOURCE_OWNER=$(echo $SOURCE_URL | awk -F '/' '{print $(NF-1)}')
           echo "SOURCE_OWNER=$SOURCE_OWNER" >> $GITHUB_ENV
           echo "SOURCE_OWNER=$SOURCE_OWNER" >> $GITHUB_OUTPUT
-          export SOURCE_REPO=$(echo "$SOURCE_URL" | awk -F '/' '{print $NF}' | sed 's/\.git$//')
+          export SOURCE_REPO=$(echo $SOURCE_URL | awk -F '/' '{print $NF}' | sed 's/\.git$//')
           echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
           echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_OUTPUT
-          export CURRENT_BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || echo "HEAD")
+          export CURRENT_BRANCH=$(git symbolic-ref --short HEAD)
           echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV
           echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_OUTPUT
-          cd "$OPENWRT_ROOT_PATH"
-          export DEVICE_NAME=$(grep 'CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' | head -1)
+          cd $OPENWRT_ROOT_PATH
+          export DEVICE_NAME=$(grep 'CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/')
           echo "DEVICE_NAME=$DEVICE_NAME" >> $GITHUB_ENV
           echo "DEVICE_NAME=$DEVICE_NAME" >> $GITHUB_OUTPUT
           export DEVICE_PLATFORM=$(grep 'CONFIG_TARGET_ARCH_PACKAGES' .config | awk -F '"' '{print $2}')
@@ -245,10 +245,10 @@ jobs:
         id: suffix
         run: |
           case "${{ env.CONFIG_FILE }}" in
-            *openclash*)
+            *openclash)
               echo "suffix=_openclash" >> $GITHUB_ENV
               ;;
-            *passwall*)
+            *passwall)
               echo "suffix=_passwall" >> $GITHUB_ENV
               ;;
             *)
@@ -261,19 +261,19 @@ jobs:
         uses: robinraju/release-downloader@v1.12
         with:
           token: ${{ env.TOKEN }}
-          repository: ${{ github.repository }}
+          repository: ${{ secrets.GITHUB_REPOSITORY }}
           fileName: ${{ env.TOOLCHAIN_IMAGE }}.hash
           tag: ${{ env.TOOLCHAIN_TAG }}
 
       - name: Compare Toolchain Hash
         run: |
           if [ -f "$TOOLCHAIN_IMAGE.hash" ]; then
-            export RELEASE_HASH=$(cat "$TOOLCHAIN_IMAGE.hash")
+            export RELEASE_HASH=$(cat $TOOLCHAIN_IMAGE.hash)
             echo "Toolchain hash is $RELEASE_HASH"
           else
             echo "Toolchain hash not found"
           fi
-          cd "$OPENWRT_ROOT_PATH"
+          cd $OPENWRT_ROOT_PATH
           export CURRENT_HASH=$(git log --pretty=tformat:"%H" -n1 tools toolchain)
           echo "CURRENT_HASH=$CURRENT_HASH" >> $GITHUB_ENV
           echo "CURRENT_HASH=$CURRENT_HASH" >> $GITHUB_OUTPUT
@@ -286,7 +286,8 @@ jobs:
       - name: Install Feeds
         if: ${{ env.REBUILD_CHECK == 'true' }}
         run: |
-          cd "$OPENWRT_ROOT_PATH"
+          echo "Install Feeds Toolchain"
+          cd $OPENWRT_ROOT_PATH
           ./scripts/feeds clean
           ./scripts/feeds update -a
           ./scripts/feeds install -a
@@ -295,25 +296,27 @@ jobs:
         if: ${{ env.REBUILD_CHECK == 'true' }}
         run: |
           if [[ "$CONFIG_LINK" == "true" && -n "$CONFIG_URL" ]]; then
-            curl -fsSL "$CONFIG_URL" -o "$OPENWRT_ROOT_PATH/.config"
+            curl -fsSL $CONFIG_URL -o $OPENWRT_ROOT_PATH/.config
           else
-            cp "./config/$CONFIG_FILE" "$OPENWRT_ROOT_PATH/.config"
+            cp ./config/$CONFIG_FILE $OPENWRT_ROOT_PATH/.config
           fi
-          cd "$OPENWRT_ROOT_PATH"
+          cd $OPENWRT_ROOT_PATH
           make defconfig
 
       - name: Compile Tools
         if: ${{ env.REBUILD_CHECK == 'true' }}
         timeout-minutes: 60
         run: |
-          cd "$OPENWRT_ROOT_PATH"
+          cd $OPENWRT_ROOT_PATH
+          echo -e "$(nproc) Thread Compile"
           make tools/compile -j$(($(nproc) + 1)) || make tools/compile -j1 V=s
 
       - name: Compile Toolchain
         if: ${{ env.REBUILD_CHECK == 'true' }}
         timeout-minutes: 120
         run: |
-          cd "$OPENWRT_ROOT_PATH"
+          cd $OPENWRT_ROOT_PATH
+          echo -e "$(nproc) Thread Compile"
           make toolchain/compile -j$(($(nproc) + 1)) || make toolchain/compile -j1 V=s
           rm -rf .config dl bin
 
@@ -322,19 +325,13 @@ jobs:
         if: ${{ env.REBUILD_CHECK == 'true' }}
         run: |
           cd workspace
-          mksquashfs openwrt "$TOOLCHAIN_IMAGE.img" -force-gid 1001 -force-uid 1001 -comp zstd -Xcompression-level 19
-          mkdir -p "$GITHUB_WORKSPACE/output"
-          if [ "${{ fromJSON(env.SPLIT_TOOLCHAIN) }}" = "true" ]; then
-            echo "Splitting toolchain image into 1GB parts..."
-            split -d -b 1G "$TOOLCHAIN_IMAGE.img" "$GITHUB_WORKSPACE/output/$TOOLCHAIN_IMAGE.img."
-            rm -f "$TOOLCHAIN_IMAGE.img"
-          else
-            echo "Toolchain image will not be split."
-            mv "$TOOLCHAIN_IMAGE.img" "$GITHUB_WORKSPACE/output/"
-          fi
-          cd "$OPENWRT_ROOT_PATH"
-          echo "$CURRENT_HASH" > "$GITHUB_WORKSPACE/output/$TOOLCHAIN_IMAGE.hash"
-          ls -lh "$GITHUB_WORKSPACE/output"
+          mksquashfs openwrt $TOOLCHAIN_IMAGE -force-gid 1001 -force-uid 1001 -comp zstd -Xcompression-level 19
+          mkdir -p $GITHUB_WORKSPACE/output
+          split -d -b 1G $TOOLCHAIN_IMAGE $GITHUB_WORKSPACE/output/$TOOLCHAIN_IMAGE.img.
+          rm -f $TOOLCHAIN_IMAGE
+          cd $OPENWRT_ROOT_PATH
+          echo $CURRENT_HASH > $GITHUB_WORKSPACE/output/$TOOLCHAIN_IMAGE.hash
+          ls -lh $GITHUB_WORKSPACE/output
 
       - name: Delete Old Toolchain Assets From Release
         if: ${{ env.REBUILD_CHECK == 'true' }}
@@ -363,7 +360,7 @@ jobs:
         run: |
           cd workspace
           if [[ "$REBUILD_CHECK" == "true" ]]; then
-            rm -rf "$TOOLCHAIN_IMAGE" output
+            rm -rf $TOOLCHAIN_IMAGE output
           else
             rm -rf openwrt
           fi
@@ -373,79 +370,166 @@ jobs:
         uses: robinraju/release-downloader@v1.12
         with:
           token: ${{ env.TOKEN }}
-          repository: ${{ github.repository }}
-          fileName: |
-            ${{ env.TOOLCHAIN_IMAGE }}.img
-            ${{ env.TOOLCHAIN_IMAGE }}.img.*
-            ${{ env.TOOLCHAIN_IMAGE }}.hash
+          repository: ${{ secrets.GITHUB_REPOSITORY }}
+          fileName: ${{ env.TOOLCHAIN_IMAGE }}.img.*
           tag: ${{ env.TOOLCHAIN_TAG }}
           out-file-path: workspace
-          fail-if-not-found: false
 
       - name: Prepare Toolchain Image
         if: ${{ steps.toolchain.outcome == 'skipped' }}
         run: |
           cd workspace
-          if ls "$TOOLCHAIN_IMAGE.img."* >/dev/null 2>&1; then
-            echo "Reconstructing split toolchain image..."
-            cat "$TOOLCHAIN_IMAGE.img."* > "$TOOLCHAIN_IMAGE.img"
-            rm -f "$TOOLCHAIN_IMAGE.img."*
-          elif [ -f "$TOOLCHAIN_IMAGE.img" ]; then
-            echo "Using single toolchain image."
-          else
-            echo "Error: No toolchain image found after download."
-            ls -la
-            exit 1
-          fi
+          for i in {00..09}; do
+            if [ -f "$TOOLCHAIN_IMAGE.img.$i" ]; then
+              cat $TOOLCHAIN_IMAGE.img.$i >> $TOOLCHAIN_IMAGE.img
+              rm -f $TOOLCHAIN_IMAGE.img.$i
+            fi
+          done
           mkdir -p openwrt-ro openwrt workdir overlay
-          sudo mount -o loop "$TOOLCHAIN_IMAGE.img" openwrt-ro
+          sudo mount -o loop $TOOLCHAIN_IMAGE.img openwrt-ro
           sudo mount -t overlay overlay -o lowerdir=openwrt-ro,upperdir=overlay,workdir=workdir openwrt
 
       - name: Update Source Code
         run: |
-          cd "$OPENWRT_ROOT_PATH"
+          cd $OPENWRT_ROOT_PATH
           git config --global user.name "github-actions"
           git config --global user.email "github-actions@github.com"
-          git fetch upstream "$SOURCE_BRANCH"
-          git merge upstream/"$SOURCE_BRANCH"
+          git fetch upstream $SOURCE_BRANCH
+          git merge upstream/$SOURCE_BRANCH
 
       - name: Load Custom Feeds
         run: |
-          cp "./scripts/$FEEDS_SH" "$OPENWRT_ROOT_PATH/$FEEDS_SH"
-          cd "$OPENWRT_ROOT_PATH"
-          chmod +x "./$FEEDS_SH" && "./$FEEDS_SH"
+          cp ./scripts/$FEEDS_SH $OPENWRT_ROOT_PATH/$FEEDS_SH
+          cd $OPENWRT_ROOT_PATH
+          chmod +x ./$FEEDS_SH && ./$FEEDS_SH
 
       - name: Install Feeds
         run: |
-          cp "./scripts/$FEEDS_PKG_SH" "$OPENWRT_ROOT_PATH/$FEEDS_PKG_SH"
-          cd "$OPENWRT_ROOT_PATH"
+          cp ./scripts/$FEEDS_PKG_SH $OPENWRT_ROOT_PATH/$FEEDS_PKG_SH
+          cd $OPENWRT_ROOT_PATH
           ./scripts/feeds clean
           ./scripts/feeds update -a
-          chmod +x "./$FEEDS_PKG_SH" && "./$FEEDS_PKG_SH"
+          chmod +x ./$FEEDS_PKG_SH && ./$FEEDS_PKG_SH
           ./scripts/feeds update -a
           ./scripts/feeds install -a
 
       - name: Replace Vermagic
-        if: ${{ fromJSON(env.VERMAGIC) }}
+        if: ${{ env.VERMAGIC == 'true' }}
         run: |
           snapshot_version="${SOURCE_BRANCH#openwrt-}"
-          release_version=$(curl -s "https://api.github.com/repos/openwrt/openwrt/tags" \
+          release_version=$(curl -s https://api.github.com/repos/openwrt/openwrt/tags \
             | grep -m1 -oE "\"name\":\s*\"v${snapshot_version}\.[^\"]+\"" \
             | cut -d'"' -f4 | sed 's/^v//')
-          if [[ "${{ env.VERMAGIC_OPT }}" == "true" ]]; then
+          if [[ "$VERMAGIC_OPT" == "true" ]]; then
             version="${snapshot_version}-SNAPSHOT"
           else
             version="${release_version}"
           fi
-          kmods=$(curl -s "https://downloads.openwrt.org/releases/${version}/targets/${DEVICE_TARGET}/${DEVICE_SUBTARGET}/kmods/" \
+          kmods=$(curl -s https://downloads.openwrt.org/releases/${version}/targets/${DEVICE_TARGET}/${DEVICE_SUBTARGET}/kmods/ \
             | grep -oP '<td class="n"><a href="\K[^/]+|<td class="d">\K[^<]+' \
             | paste -d '|' - - | sort -t '|' -k2 | head -n1 | cut -d '|' -f1)
           echo "src/gz openwrt_kmods https://downloads.openwrt.org/releases/${version}/targets/${DEVICE_TARGET}/${DEVICE_SUBTARGET}/kmods/${kmods}" >> ./custom/files/etc/opkg/customfeeds.conf
-          cd "$OPENWRT_ROOT_PATH"
-          if grep -q '^CONFIG_VERSION_REPO=' ./.config; then
-            sed -i "s|^CONFIG_VERSION_REPO=.*|CONFIG_VERSION_REPO=\"https://downloads.openwrt.org/releases/${version}\"|" ./.config
-          else
-            echo -e "\nCONFIG_VERSION_REPO=\"https://downloads.openwrt.org/releases/${version}\"" >> ./.config
-          fi
+          cd $OPENWRT_ROOT_PATH
+          grep -q '^CONFIG_VERSION_REPO=' ./.config \
+            && sed -i "s|^CONFIG_VERSION_REPO=.*|CONFIG_VERSION_REPO=\"https://downloads.openwrt.org/releases/${version}\"|" ./.config \
+            || echo -e "\nCONFIG_VERSION_REPO=\"https://downloads.openwrt.org/releases/${version}\"" >> ./.config
           echo "$kmods" | sed 's/.*-//' > .vermagic
           sed -i -e 's/^\(.\).*vermagic$/\1cp $(TOPDIR)\/.vermagic $(LINUX_DIR)\/.vermagic/' ./include/kernel-defaults.mk
+
+      - name: Load Custom Configuration
+        run: |
+          if [[ "$CONFIG_LINK" == "true" && -n "$CONFIG_URL" ]]; then
+            curl -fsSL $CONFIG_URL -o $OPENWRT_ROOT_PATH/.config
+          else
+            cp ./config/$CONFIG_FILE $OPENWRT_ROOT_PATH/.config
+          fi
+          cd $OPENWRT_ROOT_PATH
+          make defconfig
+          mkdir bin
+          cp .config ./bin/build.config
+
+      - name: Upload Config To Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: Build-Config
+          path: ${{ env.OPENWRT_ROOT_PATH }}/bin/build.config
+          retention-days: 7
+
+      - name: Load DIY
+        run: |
+          cp ./scripts/$DIY_SH $OPENWRT_ROOT_PATH/
+          mv ./custom $OPENWRT_ROOT_PATH/
+          cd $OPENWRT_ROOT_PATH
+          chmod +x ./$DIY_SH && ./$DIY_SH
+
+      - name: Download Packages
+        timeout-minutes: 30
+        run: |
+          cd $OPENWRT_ROOT_PATH
+          retry_count=0
+          until make download -j10 || [ $retry_count -ge $MAX_RETRIES ]; do
+            retry_count=$((retry_count+1))
+            echo "Download failed, retrying in $RETRY_DELAY seconds... ($retry_count/$MAX_RETRIES)"
+            sleep $RETRY_DELAY
+          done
+          find dl -size -1024c -exec ls -l {} \;
+          find dl -size -1024c -exec rm -f {} \;
+
+      - name: Compile Packages
+        timeout-minutes: 180
+        run: |
+          cd $OPENWRT_ROOT_PATH
+          echo -e "$(nproc) Thread Compile"
+          make clean
+          make buildinfo
+          make diffconfig buildversion feedsversion
+          make target/compile -j$(($(nproc) + 1)) IGNORE_ERRORS="m n" BUILD_LOG=1 || \
+          yes n | make target/compile -j1 V=s IGNORE_ERRORS=1
+          make package/compile -j$(($(nproc) + 1)) IGNORE_ERRORS=1 || make package/compile -j1 V=s IGNORE_ERRORS=1
+          make package/index
+
+      - name: Generate Firmware
+        timeout-minutes: 60
+        run: |
+          cd $OPENWRT_ROOT_PATH
+          make package/install -j$(($(nproc) + 1)) || make package/install -j1 V=s
+          make target/install -j$(($(nproc) + 1)) || make target/install -j1 V=s
+          make json_overview_image_info
+          make checksum
+
+      - name: Upload Bin To Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.SOURCE_REPO }}-${{ env.DEVICE_NAME }}-${{ env.BUILD_DATE }}
+          path: ${{ env.OPENWRT_ROOT_PATH }}/bin
+          retention-days: 7
+
+      - name: Organize Files
+        if: ${{ env.FIRMWARE_RELEASE == 'true' }}
+        run: |
+          cd $OPENWRT_ROOT_PATH/bin/targets/$DEVICE_TARGET/$DEVICE_SUBTARGET
+          rm -rf packages feeds.buildinfo profiles.json version.buildinfo
+          df -hT $PWD
+
+      - name: Deploy Files To Release
+        if: ${{ env.FIRMWARE_RELEASE == 'true' }}
+        uses: ncipollo/release-action@v1
+        with:
+          token: ${{ env.TOKEN }}
+          name: ${{ env.SOURCE_REPO }}_${{ env.SOURCE_BRANCH }}_${{ env.DEVICE_NAME }}${{ env.suffix }}
+          commit: ${{ env.CURRENT_BRANCH }}
+          tag: ${{ env.SOURCE_REPO }}_${{ env.SOURCE_BRANCH }}_${{ env.DEVICE_NAME }}${{ env.suffix }}
+          artifacts: ${{ env.OPENWRT_ROOT_PATH }}/bin/targets/${{ env.DEVICE_TARGET }}/${{ env.DEVICE_SUBTARGET }}/*
+          replacesArtifacts: true
+          allowUpdates: true
+          prerelease: false
+          body: |
+            ### Build Information
+            ---
+            - Source Code: ${{ env.SOURCE_URL }}
+            - Source Code Branch: ${{ env.SOURCE_BRANCH }}
+            - Device Target: ${{ env.DEVICE_TARGET }}
+            - Device Subtarget: ${{ env.DEVICE_SUBTARGET }}
+            - Device Platform: ${{ env.DEVICE_PLATFORM }}
+            - Device Name: ${{ env.DEVICE_NAME }}
+            - Build Date: ${{ env.BUILD_DATE }}
